### ISSUE TITLE
add config reset

### ISSUE THREAD

**Issue by realtaraharris** [nodesource/nscm#15]
this part works well:

```
% nscm config get some-setting
some-default-setting-string-here
% nscm config set some-setting "something-not-default"
```

but it would be really nice if `nscm` let you do this:

```
% nscm config reset some-setting
some-default-setting-string-here
```

**Comment by bnb** [comment]
Would this set `some-setting` to the `nscm` default, or the previous value for `some-setting`?

**Comment by realtaraharris** [comment]
@bnb `nscm` ships with a built-in default, and it seems like the least surprising thing would be to have it reset to that default. (Also, remembering the previous setting would require that we maintain a history of settings values, which complicates things further...)

Thoughts?

**Comment by bnb** [comment]
@maxharris9 +1 to resetting it to the default  that `nscm` ships with 👍
