### ISSUE TITLE
[signin] add status message after successful login

### ISSUE THREAD

**Issue by tmpvar** [nodesource/nscm#9]
currently

__email/password__

```
$ nscm signin
email: elijah@nodesource.com
password:
$
```
__SSO__

```
$ nscm signin --github
a browser will launch and ask you to sign in.

once you have the authorization code, please enter it here: ...
$
```

Neither of these flows tell the user that they have logged in, but it would be nice to show them that they have logged in and possibly show what their registry url is.

**Comment by julianduque** [comment]
Landed in 1.6.1
